### ISSUE TITLE
Créer les quizs dans Notion ?

### ISSUE THREAD

**Issue by raphodn** [quiz-anthropocene/admin-backend#175]
## Objectif

Avoir un seul véritable back-office pour la création du contenu.

## Détails

Actuellement Notion sert à créer les Questions et les Tags, alors que le Backend sert à la création des Quizs (ainsi qu'à la validation du contenu, le recueil des stats, ...). 
Il semblerait que ce soit possible dans Notion de faire des liens entre des tables, et donc de créer des quizs à partir de X questions.
Que nous renvoie ensuite l'API ? (via le package `notion-py`)

**Comment by lodi-g** [comment]
Une idée comme ca, mais si on crée les quizzs dans Notion on peut complètement les importer lors du build du frontend, se passant alors completement du backend (a part pour les fonctionnalitées interactives comme l'ajout d'un commentaire).

A explorer?

**Comment by raphodn** [comment]
À creuser en effet, en fait pour l'instant le Backend permet aussi de faire des checks sur la validité et la qualité de la donnée, surtout pour les questions (par exemple si type=VF alors answer_correct=a or b), moins pour les quizs.
Et dans l'archi actuelle les stats sont rattachés à des ids de questions ou de quizs donc doivent exister en base dans le Backend.

Mais on peut tout repenser oui, pour éviter d'avoir 2 back office comme actuellement.

Ca n'existe pas django-notion ? 😅

**Comment by raphodn** [comment]
Les quizs sont maintenant créés dans l'interface contributeur - cf https://github.com/quiz-anthropocene/admin-backend/issues/1707
