### ISSUE TITLE
Mettre en avant les questions taggés 'Actualité'

### ISSUE THREAD

**Issue by raphodn** [quiz-anthropocene/admin-backend#29]
## Objectif

Avoir sur la home page différents blocs, dont une sections 'questions d'actualité'

**Comment by PYLager** [comment]
Je verrais bien une nouvelle colonne 'tag_actualité' (de type texte ou date ?), pour identifier formellement ces questions, les filtrer dans la partie actu et les réutiliser dans le pool standard.

**Comment by raphodn** [comment]
le repo du frontend a été déplacé. noté ici : https://github.com/quiz-anthropocene/public-frontend/issues/543
