### ISSUE TITLE
Ajouter la durée estimée pour réaliser le quiz

### ISSUE THREAD

**Issue by Sarma38** [quiz-anthropocene/admin-backend#351]
Mention : Durée estimée : X minutes, avec X =nb de questions x 1,5 arrondi à la minute

**Comment by raphodn** [comment]
Récupérer d'abord des stats sur le temps pris par quiz

**Comment by raphodn** [comment]
> Récupérer d'abord des stats sur le temps pris par quiz

https://github.com/raphodn/know-your-planet/pull/1287
