### ISSUE TITLE
Avoir un espace utilisateur (session, cookies)

### ISSUE THREAD

**Issue by raphodn** [quiz-anthropocene/admin-backend#66]
## Objectif

Sans login, garder l'historique de l'utilisateur sur une session donné, pour lui permettre de voir ses statistiques

## Détails

Un utilisateur parcourt l'application, répond à un quiz, et à des questions en vrac. Il peut ensuite accéder à son espace utilisateur pour voir ses résultats. On peut aussi éviter de lui re-proposer les mêmes questions.

Utilisation du localstorage ? cookie ?

Issue potentiellement liée à https://github.com/raphodn/know-your-planet/issues/31

**Comment by bguivarch** [comment]
On utilise ce package sur un autre projet:https://github.com/robinvdvleuten/vuex-persistedstate
il est très simple a utiliser et permet de garder l'historique du store dans le localstorage, session ou en cookies.
